#include <Python.h>
#include <jni.h>
#include <filesystem>
#include <iostream>
#include <string>

// Generated by xxd -i Hello.py at build time.
// Provides: unsigned char Hello_py[];  unsigned int Hello_py_len;
#include "hello_py_data.h"

// ── Python ────────────────────────────────────────────────────────────────────
// Loads Hello.py (embedded at compile time) into the interpreter, then calls
// the greet() function defined in it.

std::string python_greet(const std::string& name) {
    Py_Initialize();

    // Run the embedded Hello.py source to define greet().
    // Hello_py is not null-terminated, so we copy it into a std::string first.
    std::string src(reinterpret_cast<const char*>(Hello_py), Hello_py_len);
    PyRun_SimpleString(src.c_str());

    // Call greet(name) via the C API.
    PyObject* mod    = PyImport_AddModule("__main__");
    PyObject* fn     = PyObject_GetAttrString(mod, "greet");
    PyObject* arg    = PyUnicode_FromString(name.c_str());
    PyObject* res    = PyObject_CallFunction(fn, "O", arg);
    std::string result(PyUnicode_AsUTF8(res));

    Py_DECREF(res);
    Py_DECREF(arg);
    Py_DECREF(fn);
    Py_Finalize();
    return result;
}

// ── Java ──────────────────────────────────────────────────────────────────────
// Spins up an embedded JVM, loads Hello.class from the jar, calls greet().

std::string java_greet(const std::string& jar_path, const std::string& name) {
    JavaVM* jvm;
    JNIEnv* env;

    std::string cp = "-Djava.class.path=" + jar_path;
    JavaVMOption opt{};
    opt.optionString = const_cast<char*>(cp.c_str());

    JavaVMInitArgs args{};
    args.version  = JNI_VERSION_1_8;
    args.nOptions = 1;
    args.options  = &opt;

    JNI_CreateJavaVM(&jvm, reinterpret_cast<void**>(&env), &args);

    jclass    cls  = env->FindClass("Hello");
    jmethodID mid  = env->GetStaticMethodID(cls, "greet", "(Ljava/lang/String;)Ljava/lang/String;");
    jstring   jstr = env->NewStringUTF(name.c_str());
    auto      jres = static_cast<jstring>(env->CallStaticObjectMethod(cls, mid, jstr));

    const char* raw = env->GetStringUTFChars(jres, nullptr);
    std::string result(raw);
    env->ReleaseStringUTFChars(jres, raw);

    jvm->DestroyJavaVM();
    return result;
}

// ── main ──────────────────────────────────────────────────────────────────────

int main(int argc, char* argv[]) {
    namespace fs = std::filesystem;

    // HelloJar.jar is placed next to the executable by CMake (POST_BUILD).
    std::string jar = (fs::path(argv[0]).parent_path() / "HelloJar.jar").string();

    std::cout << python_greet("World") << "\n";
    std::cout << java_greet(jar, "World") << "\n";
}
