/**
 * native_math.cpp — C++ implementation of com.tutorial.NativeMath native methods.
 *
 * JNI naming convention (generated by javac -h):
 *   Java_<package_dots_to_underscores>_<ClassName>_<methodName>
 *   e.g.  com.tutorial.NativeMath.add  →  Java_com_tutorial_NativeMath_add
 *
 * Key JNI types:
 *   jint        → Java int (32-bit)
 *   jlong       → Java long (64-bit)
 *   jdouble     → Java double
 *   jboolean    → Java boolean (JNI_TRUE / JNI_FALSE)
 *   jstring     → Java String (opaque handle; use Get/ReleaseStringUTFChars)
 *   jdoubleArray→ Java double[] (opaque handle; use Get/ReleaseDoubleArrayElements)
 */

// The header is generated by javac -h and placed in jni_headers/ by CMake.
// It contains the exact JNIEXPORT signatures we must match.
#include "com_tutorial_NativeMath.h"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <string>
#include <vector>

// ── Arithmetic ────────────────────────────────────────────────────────────────

JNIEXPORT jint JNICALL
Java_com_tutorial_NativeMath_add(JNIEnv*, jclass, jint a, jint b) {
    return a + b;
}

JNIEXPORT jint JNICALL
Java_com_tutorial_NativeMath_multiply(JNIEnv*, jclass, jint a, jint b) {
    return a * b;
}

JNIEXPORT jdouble JNICALL
Java_com_tutorial_NativeMath_power(JNIEnv*, jclass, jdouble base, jint exp) {
    double result = 1.0;
    for (int i = 0; i < exp; ++i) result *= base;
    return result;
}

// ── Number theory ─────────────────────────────────────────────────────────────

JNIEXPORT jlong JNICALL
Java_com_tutorial_NativeMath_factorial(JNIEnv*, jclass, jint n) {
    if (n < 0) return -1;
    long long result = 1;
    for (int i = 2; i <= n; ++i) result *= i;
    return (jlong)result;
}

JNIEXPORT jboolean JNICALL
Java_com_tutorial_NativeMath_isPrime(JNIEnv*, jclass, jint n) {
    if (n < 2) return JNI_FALSE;
    for (int i = 2; (long long)i * i <= n; ++i)
        if (n % i == 0) return JNI_FALSE;
    return JNI_TRUE;
}

JNIEXPORT jlong JNICALL
Java_com_tutorial_NativeMath_fibonacci(JNIEnv*, jclass, jint n) {
    if (n <= 0) return 0;
    if (n == 1) return 1;
    long long a = 0, b = 1;
    for (int i = 2; i <= n; ++i) {
        long long tmp = a + b;
        a = b;
        b = tmp;
    }
    return (jlong)b;
}

// ── String operations ─────────────────────────────────────────────────────────

JNIEXPORT jstring JNICALL
Java_com_tutorial_NativeMath_reverseString(JNIEnv* env, jclass, jstring jstr) {
    const char* chars = env->GetStringUTFChars(jstr, nullptr);
    std::string s(chars);
    env->ReleaseStringUTFChars(jstr, chars);

    std::reverse(s.begin(), s.end());
    return env->NewStringUTF(s.c_str());
}

JNIEXPORT jboolean JNICALL
Java_com_tutorial_NativeMath_isPalindrome(JNIEnv* env, jclass, jstring jstr) {
    const char* chars = env->GetStringUTFChars(jstr, nullptr);
    std::string s(chars);
    env->ReleaseStringUTFChars(jstr, chars);

    // Case-insensitive: convert to lowercase then compare
    std::string lower(s.size(), '\0');
    std::transform(s.begin(), s.end(), lower.begin(), ::tolower);

    std::string rev(lower.rbegin(), lower.rend());
    return (lower == rev) ? JNI_TRUE : JNI_FALSE;
}

JNIEXPORT jint JNICALL
Java_com_tutorial_NativeMath_countVowels(JNIEnv* env, jclass, jstring jstr) {
    const char* chars = env->GetStringUTFChars(jstr, nullptr);
    std::string s(chars);
    env->ReleaseStringUTFChars(jstr, chars);

    int count = 0;
    for (char c : s) {
        char lc = (char)tolower((unsigned char)c);
        if (lc == 'a' || lc == 'e' || lc == 'i' || lc == 'o' || lc == 'u')
            ++count;
    }
    return (jint)count;
}

// ── Array operations ──────────────────────────────────────────────────────────

JNIEXPORT jdouble JNICALL
Java_com_tutorial_NativeMath_dotProduct(JNIEnv* env, jclass,
                                        jdoubleArray ja, jdoubleArray jb) {
    jsize len = env->GetArrayLength(ja);

    // GetDoubleArrayElements: pins the array in memory (or copies to a buffer)
    jdouble* a = env->GetDoubleArrayElements(ja, nullptr);
    jdouble* b = env->GetDoubleArrayElements(jb, nullptr);

    double result = 0.0;
    for (jsize i = 0; i < len; ++i) result += a[i] * b[i];

    // JNI_ABORT: don't copy back (we only read the data)
    env->ReleaseDoubleArrayElements(ja, a, JNI_ABORT);
    env->ReleaseDoubleArrayElements(jb, b, JNI_ABORT);

    return result;
}

JNIEXPORT jdoubleArray JNICALL
Java_com_tutorial_NativeMath_sortDescending(JNIEnv* env, jclass,
                                             jdoubleArray jarr) {
    jsize len = env->GetArrayLength(jarr);
    jdouble* elems = env->GetDoubleArrayElements(jarr, nullptr);

    // Copy to a std::vector, sort descending, then return a new Java array
    std::vector<double> v(elems, elems + len);
    env->ReleaseDoubleArrayElements(jarr, elems, JNI_ABORT);

    std::sort(v.begin(), v.end(), std::greater<double>());

    jdoubleArray result = env->NewDoubleArray(len);
    env->SetDoubleArrayRegion(result, 0, len, v.data());
    return result;
}
